name: Delivery

on: 
  push:
    branches:
      - main

env:
  GCP_PROJECT: pulumi-demo-2021

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Setup golangci
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.6.4
      - name: Interact with gotestsum
        run: gotestsum --format short-verbose

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: google-github-actions/setup-gcloud@master
          with:
            version: '290.0.1'
            project_id: ${ GCP_PROJECT }
            service_account_key: ${{ secrets.SA_KEY }}
            export_default_credentials: true
        - name: Configure Docker
          run: gcloud auth configure-docker
        - name: Build
          run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/helloworld:latest .
        - name: Push
          run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/helloworld:latest
        - name: Deploy
          run: |
            gcloud run deploy helloworld \
            --region asia-northeast1 \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/helloworld \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT }}
