name: Delivery

on: 
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: google-github-actions/setup-gcloud@master
          with:
            version: '290.0.1'
            project_id: ${{ secrets.GCP_PROJECT }}
            service_account_key: ${{ secrets.SA_KEY }}
            export_default_credentials: true
        - name: Configure Docker
          run: gcloud auth configure-docker
        - name: Build
          run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/helloworld:latest .
        - name: Push
          run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/helloworld:latest
        - name: Deploy
          run: |
            gcloud run deploy helloworld \
            --region asia-northeast1 \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/helloworld \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT }}
